version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: estapar-mysql
    restart: always
    environment:
      MYSQL_DATABASE: estapar_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  simulator:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: estapar-simulator
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy