services:
  # Banco de Dados
  mysql:
    image: mysql:8.0
    container_name: estapar_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estapar_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  # Simulador da Estapar
  # IMPORTANTE: O simulador tenta enviar webhooks para localhost:3003.
  # Usando network_mode: "host", ele consegue acessar sua aplicação Java rodando na IDE.
  # (Isso funciona nativamente no Linux. No Windows/Mac, pode haver limitações,
  # sendo necessário rodar a aplicação Java também via Docker ou ajustar o host).
  simulator:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: estapar_simulator
    network_mode: "host"
    depends_on:
      - mysql